# This is a basic workflow to help you get started with Actions

name: Update

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main
  schedule:
    # Every hour *not* on the hour (to save NSW Health's poor servers)
    # (Run at 55 minutes past so that the follow-on cron job in the main repo
    # has access to fairly fresh data)
     - cron:  '55 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: pip install dependencies
      run: pip install -r requirements.txt

    - name: Run hourly data updates
      run: ./scripts.hourly/update.py

    - name: Commit files
      run: |
        git pull # get any data pushed by previous steps
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data_cache
        git commit -m "Add latest dataset" -a || true
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
